#!/bin/sh
case "$1" in
    start)
        echo 3 > /proc/sys/vm/drop_caches;
        echo sstf > /sys/block/sdb/queue/scheduler
        ;;
    stop)
        exit 1
        ;;
    *)
        exit 1
        ;;
esac

exit 0